### ISSUE TITLE
Add option to open master branch link

### ISSUE THREAD

**Issue by itaditya** [qinezh/vscode-gitlink#22]
Hey my usecase for this plugin is that somebody wants url for a file and I'm in my editor so I can CMD + P the file and copy its link. However mostly I'm in a different branch and they won't have my branch so I have to manually change the branch name from the link to **master**. If in the menu there was option to *Copy Online Link for master* then that would be really useful.

**Comment by qinezh** [comment]
That would cause extra step to copy the link for most user scenarios, if there is an option before the copy. I would prefer to make the extension handy for most cases, instead of full functionalities.

And the request is also a little bit tricky, as the file from your branch and master branch might be different and the line number of your selection would be inaccurate and unexpected.
